language: ruby
sudo: false
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - xvfb-run bundle exec rake
